Airdrop on top of advancements
sismo-core/sismo-protocol pull request #45
Opened 2022-12-02 17:27 UTC by yum0e

2022-12-06 10:43 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGatedState.sol
> +    } else {
would do:
`else if (block.chainid == 31337 || block.chainid == 1337) { local } else throw`  

(so we sure we don't deploy something weird on a chain

2022-12-06 10:43 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGatedState.sol
> +  constructor(uint256 _gatedBadge) {
at sismo we use _ for storage

2022-12-07 08:33 UTC, leosayous21 commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  Badges public badges;
Use immutable here

2022-12-07 08:33 UTC, leosayous21 commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  /**************************************
Remove the use of storage slot

2022-12-07 08:33 UTC, leosayous21 commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +    uint256 badgeTokenId,
Implement array directly here + minimalValue

2022-12-07 08:35 UTC, leosayous21 commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  Badges public badges;
In fact it's not possible, `Cannot write to immutable here: Immutable variables cannot be initialized inside an if statement`

2022-12-07 12:22 UTC, dhadrien requested changes

2022-12-07 12:22 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +    uint256 gatedBadgeMinimumValue,
balanceMin

=> will need to add in comments that balance == level for a badge

2022-12-07 12:22 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +    checkBadgesOwnership(
does not do what it says it does

2022-12-07 12:22 UTC, dhadrien commented on contracts/tests/MockGatedERC721.sol
> +  function _markNullifierAsUsed(uint256 nullifier) internal {
_setNullifierAsUsed

2022-12-07 12:22 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  function checkBadgesOwnership(
does not do what it says it does

2022-12-07 12:22 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  modifier onlyBadgeOwner(
does not do what it says it does

2022-12-07 12:22 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  function _buildRequestAndProof(
maybe _decodeRequestAndProofFromBytes

2022-12-07 12:22 UTC, dhadrien commented on contracts/tests/MockGatedERC721.sol
> +    bytes memory data
rename data to sismoProofData 

This is the hard part, they must understand that this is what they will receive via the off-chain prove with sismo flow

2022-12-07 12:22 UTC, dhadrien commented on contracts/tests/MockGatedERC721.sol
> +    proveWithSismo(HYDRA_S1_ACCOUNTBOUND_ATTESTER, data);
I think we should check if attestation destination == to

2022-12-07 12:22 UTC, dhadrien commented on contracts/tests/MockGatedERC721.sol
> +    proveWithSismo(HYDRA_S1_ACCOUNTBOUND_ATTESTER, data);
should also check whether attestation value >= badgeLevelMin

2022-12-07 15:48 UTC, dhadrien commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +  function checkAccountBadgesOrSismoProofs(
I think it still does not check min value with proof with sismo.

I can generate an attestation of level 0

2022-12-08 14:51 UTC, leosayous21 commented on contracts/core/libs/sismo-gated/SismoGated.sol
> +    bool isInclusive
Very hard to know that it corresponds to an AND or OR operation i think

2022-12-08 15:26 UTC, leosayous21 commented on contracts/tests/MockGatedERC721.sol
> +    uint256 nullifier = _getNulliferForAddress(to);
How you can have only one nullifier but 2 badges? 
GATED_BADGE_TOKEN_ID is used directly inside the `_getNulliferForAddress` function here

2022-12-08 15:26 UTC, leosayous21 commented on contracts/tests/MockGatedERC721.sol
> +    _transfer(from, to, tokenId);
This function can't work as you could send your NFT to anyone

2022-12-08 15:26 UTC, leosayous21 commented on contracts/tests/MockGatedERC721.sol
> +    for (uint256 i = 0; i < values.length; i++) {
You don't check the different tokenID here

2022-12-08 15:38 UTC, leosayous21 commented on contracts/tests/MockGatedERC721.sol
> +    safeTransferFrom(from, to, tokenId);
We don't check the nullifier here?

2023-01-11 11:59 UTC, Crocozyabro commented
review tests👍

2023-01-12 15:09 UTC, dhadrien commented on contracts/tests/zk-drop/ZKBadgeboundERC721.sol
> +  uint256 public immutable MERGOOOR_PASS_BADGE_TOKEN_ID;
rename to GATING_BADGE_TOKEN_ID

2023-01-12 15:10 UTC, dhadrien commented on contracts/tests/zk-drop/ZKBadgeboundERC721.sol
> +    uint256 passTokenId
rename

2023-01-12 15:10 UTC, dhadrien commented on tasks/deploy-tasks/tests/deploy-zk-badgebound-erc721.task.ts
> +  .addParam('passTokenId', 'Token ID of the pass token')
rename param

2023-01-16 19:29 UTC, merged